In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns

In [4]:
np.set_printoptions(suppress=True)
pd.set_option('display.max_columns',8000)
pd.set_option('display.max_rows',7000)

In [4]:
imagepath='C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/images'
Test_images='C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/Test_images'

In [5]:
train=pd.read_csv('C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/train.csv')
test=pd.read_csv('C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/test_vc2kHdQ.csv')

In [6]:
train.head(10)

image_names         Labels
0    1503.jpg  Not Emergency
1    1420.jpg  Not Emergency
2    1764.jpg  Not Emergency
3    1356.jpg  Not Emergency
4    1117.jpg  Not Emergency
5      45.jpg      emergency
6    2313.jpg  Not Emergency
7    1657.jpg  Not Emergency
8     294.jpg      emergency
9     999.jpg  Not Emergency

In [37]:
test.head(10)

image_names
0    1960.jpg
1     668.jpg
2    2082.jpg
3     808.jpg
4    1907.jpg
5     350.jpg
6    1557.jpg
7     111.jpg
8    1952.jpg
9    1466.jpg

In [8]:
from keras.preprocessing import image
from keras.layers import Input, Lambda, Dense, Flatten
from keras.models import Model
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from glob import glob

Using TensorFlow backend.


In [11]:
image_names=list(train['image_names'].values)
image_labels=list(train['Labels'].values)

In [20]:
folders = np.unique(list(train['Labels'].values))

In [21]:
folders

array(['Not Emergency', 'emergency'], dtype='<U13')

In [15]:
import shutil
import os

In [16]:
test_images=list(test['image_names'].values)

In [30]:
for g in range(len(test_images)):
    current_test_img=test_images[g]
    shutil.move("C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/images/"+current_test_img, "C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/Test")

In [19]:
Testingimagepath='C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/Test/'

In [33]:
IMAGE_SIZE = [224, 224]

In [10]:
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
from keras.applications.resnet50 import ResNet50
from keras.applications.resnet50 import preprocess_input
from keras.layers import GlobalAveragePooling2D
from keras.layers import Dropout
from keras.applications.mobilenet_v2 import MobileNetV2
from keras.applications.mobilenet_v2 import preprocess_input

In [39]:
X=train['image_names'].values
y=train['Labels'].values

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=42)

In [48]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)


(1152,)
(1152,)
(494,)
(494,)


In [50]:
X_train_images=list(X_train)
y_train_labels=list(y_train)

In [65]:
for item in range(len(X_train_images)):
    current_train_img=X_train_images[item]
    current_train_labels=y_train_labels[item]
    shutil.move("C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/images/"+current_train_img, "C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/X_Train/"+current_train_labels)

In [66]:
X_test_images=list(X_test)
y_test_labels=list(y_test)

In [67]:
for item2 in range(len(X_test_images)):
    current_test_img=X_test_images[item2]
    current_test_labels=y_test_labels[item2]
    shutil.move("C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/images/"+current_test_img, "C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/X_test/"+current_test_labels)

In [71]:
train_datagen = ImageDataGenerator(rescale = 1./255, shear_range = 0.2,zoom_range = 0.2,
horizontal_flip = True,brightness_range=[0.5,0.3],rotation_range=0.2)

In [72]:
test_datagen = ImageDataGenerator(rescale = 1./255)

In [75]:
X_train_Imagepath='C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/X_Train'
X_test_Imagepath='C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/X_test'

In [76]:
training_set = train_datagen.flow_from_directory(X_train_Imagepath, target_size = (224, 224),batch_size = 32,
class_mode = 'categorical')

Found 1152 images belonging to 2 classes.


In [77]:
test_set = test_datagen.flow_from_directory(X_test_Imagepath,target_size = (224, 224),
batch_size = 32,class_mode = 'categorical')

Found 494 images belonging to 2 classes.


In [89]:
classes=glob('C:/Users/user/Desktop/I neuron DLNLPCV/DL DATASETS/JanataHack Computer Vision Hackathon/X_Train/*')

In [ ]:
################################################################################################

In [78]:
vgg = VGG16(input_shape=IMAGE_SIZE + [3], weights='imagenet', include_top=False)

In [79]:
for layer in vgg.layers:
    layer.trainable = False

In [90]:
vgg.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [91]:
x = Flatten()(vgg.output)
x=Dense(100, activation='relu')(x)
prediction = Dense(len(classes), activation='softmax')(x)

In [92]:
model = Model(inputs=vgg.input, outputs=prediction)

In [93]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [96]:
MODEL = model.fit_generator(training_set,validation_data=test_set,epochs=3,steps_per_epoch=len(training_set),
validation_steps=len(test_set))

Epoch 1/3
36/36 [==============================] - 674s 19s/step - loss: 0.3731 - accuracy: 0.8325 - val_loss: 0.2596 - val_accuracy: 0.8502
Epoch 2/3
36/36 [==============================] - 667s 19s/step - loss: 0.2792 - accuracy: 0.8837 - val_loss: 0.5972 - val_accuracy: 0.8644
Epoch 3/3
36/36 [==============================] - 673s 19s/step - loss: 0.2859 - accuracy: 0.8767 - val_loss: 0.6112 - val_accuracy: 0.8543


In [97]:
MODEL.history

{'val_loss': [0.25960782170295715, 0.5971511006355286, 0.6112352013587952],
 'val_accuracy': [0.8502024412155151, 0.8643724918365479, 0.8542510271072388],
 'loss': [0.37314409845405155, 0.27923231323560077, 0.28592343793974984],
 'accuracy': [0.8324653, 0.8836806, 0.8767361]}

In [ ]:
###############################################################

In [131]:
Res50=ResNet50(input_shape=IMAGE_SIZE+[3],weights= 'imagenet',include_top=False)

94658560/94653016 [==============================] - 104s 1us/step


In [132]:
for layer in Res50.layers:
    layer.trainable = False

In [146]:
modelRes50.summary()

Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_2[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 112, 112, 64) 256         conv1[0][0]                      
____________________________________________________________________________________________

In [152]:
x = Res50.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.4)(x)
predictions=Dense(len(classes),activation='softmax')(x)
modelRes50=Model(inputs = Res50.input, outputs = predictions)

In [153]:
modelRes50.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [154]:
modelRes50=modelRes50.fit_generator(training_set,validation_data=test_set,epochs=3,steps_per_epoch=len(training_set),validation_steps=len(test_set))

Epoch 1/3
36/36 [==============================] - 759s 21s/step - loss: 0.5031 - accuracy: 0.7500 - val_loss: 1.1355 - val_accuracy: 0.4312
Epoch 2/3
36/36 [==============================] - 709s 20s/step - loss: 0.2999 - accuracy: 0.8837 - val_loss: 0.7393 - val_accuracy: 0.4312
Epoch 3/3
36/36 [==============================] - 732s 20s/step - loss: 0.2743 - accuracy: 0.8932 - val_loss: 0.8585 - val_accuracy: 0.4312


In [155]:
modelRes50.history

{'val_loss': [1.1354548931121826, 0.739263653755188, 0.8584955334663391],
 'val_accuracy': [0.431174099445343, 0.431174099445343, 0.431174099445343],
 'loss': [0.5031184181571007, 0.29989079799917007, 0.2743461738444037],
 'accuracy': [0.75, 0.8836806, 0.8932292]}

In [ ]:
########################################################

In [200]:
Mobile=MobileNetV2(input_shape=IMAGE_SIZE+[3],weights= 'imagenet',include_top=False)

In [201]:
for layer in Mobile.layers:
    layer.trainable = False

In [202]:
Mobile.summary()

Model: "mobilenetv2_1.00_224"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_7 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 225, 225, 3)  0           input_7[0][0]                    
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
_______________________________________________________________________________

In [203]:
x = Mobile.output
x=GlobalAveragePooling2D()(x)
x=Dense(512,activation='relu')(x)
predictionV=Dense(len(classes),activation='softmax')(x)
modelMobile=Model(inputs =Mobile.input, outputs =predictionV)

In [207]:
modelMobile.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [208]:
modelMobile.fit_generator(training_set,validation_data=test_set,epochs=3,steps_per_epoch=len(training_set),validation_steps=len(test_set))

Epoch 1/3
36/36 [==============================] - 312s 9s/step - loss: 0.5793 - accuracy: 0.7517 - val_loss: 0.1624 - val_accuracy: 0.9069
Epoch 2/3
36/36 [==============================] - 302s 8s/step - loss: 0.2413 - accuracy: 0.9054 - val_loss: 0.2161 - val_accuracy: 0.9291
Epoch 3/3
36/36 [==============================] - 295s 8s/step - loss: 0.2149 - accuracy: 0.9184 - val_loss: 0.0475 - val_accuracy: 0.9089


model=VGG16
modelRes50=Resnet50
modelMobile=MobileNetV2

In [210]:
model.save('modelVGG16.h5')

In [211]:
Res50.save('modelRes50.h5')
Mobile.save('MobileNetV2.h5')

In [11]:
from keras.models import load_model

In [12]:
model1=load_model('modelVGG16.h5')
model2=load_model('modelRes50.h5')
model3=load_model('MobileNetV2.h5')

In [ ]:
##########################################

In [13]:
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input

In [30]:
predictions1=[]
for pic in range(len(test_images)):
    test_img=test_images[pic]
    img = image.load_img(Testingimagepath+test_img, target_size=(224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    img_data = preprocess_input(x)
    preds1 = np.argmax(model1.predict(img_data))
    predictions1.append(preds1)
    

In [98]:
predictions2=[]
for pic1 in range(len(test_images)):
    test_img1=test_images[pic1]
    img1 = image.load_img(Testingimagepath+test_img1, target_size=(224, 224))
    z = image.img_to_array(img1)
    z = np.expand_dims(z, axis=0)
    img_data=preprocess_input(z)
    preds2 = np.argmax(model2.predict(img_data), axis=1)
    predictions2.append(preds2)

In [99]:
predictions2

[77691,
 44258,
 52367,
 50706,
 34564,
 37372,
 67037,
 68041,
 61897,
 60469,
 55154,
 26376,
 55515,
 65993,
 67269,
 71512,
 67366,
 52951,
 22231,
 51708,
 29332,
 38851,
 51337,
 63346,
 62517,
 44914,
 20183,
 61125,
 67803,
 48490,
 62638,
 87077,
 47478,
 85883,
 71383,
 27776,
 65342,
 53732,
 61897,
 61307,
 63945,
 63945,
 51058,
 63670,
 47561,
 65221,
 64664,
 64789,
 47644,
 50229,
 49832,
 40712,
 38597,
 27874,
 65042,
 63945,
 42514,
 34794,
 29922,
 52367,
 49348,
 51860,
 49010,
 47887,
 78581,
 50885,
 63945,
 48181,
 22231,
 50319,
 24328,
 63355,
 70089,
 75643,
 65239,
 80293,
 36176,
 63945,
 50903,
 54802,
 48181,
 48658,
 51006,
 68041,
 40708,
 48837,
 60647,
 94495,
 50885,
 69464,
 64593,
 64565,
 67269,
 65993,
 15586,
 50350,
 53196,
 64789,
 66734,
 47784,
 51708,
 67442,
 33511,
 40645,
 52951,
 87621,
 66734,
 61897,
 8642,
 34564,
 26350,
 63945,
 27874,
 18117,
 52769,
 62638,
 46610,
 18534,
 51657,
 36612,
 55976,
 65993,
 84425,
 48837,
 48837,
 

In [82]:
from keras.applications.mobilenet_v2 import preprocess_input

In [83]:
predictions3=[]
for pic2 in range(len(test_images)):
    test_img2=test_images[pic2]
    img2 = image.load_img(Testingimagepath+test_img2, target_size=(224, 224))
    y = image.img_to_array(img2)
    y = np.expand_dims(y, axis=1)
    img_data = preprocess_input(y)
    preds3 = np.argmax(model3.predict(img_data),axis=1)
    predictions3.append(preds3)

In [66]:
predictions3

[array([[[0, 0, 0, ..., 0, 0, 0],
         [3, 0, 0, ..., 0, 3, 0],
         [3, 2, 0, ..., 0, 4, 0],
         ...,
         [4, 2, 0, ..., 1, 0, 0],
         [4, 2, 4, ..., 2, 0, 0],
         [0, 2, 0, ..., 2, 0, 0]]], dtype=int64),
 array([[[0, 2, 3, ..., 0, 3, 0],
         [2, 1, 3, ..., 1, 3, 0],
         [2, 1, 3, ..., 1, 3, 0],
         ...,
         [0, 2, 2, ..., 0, 4, 0],
         [6, 2, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]], dtype=int64),
 array([[[3, 0, 0, ..., 0, 0, 0],
         [3, 0, 0, ..., 2, 2, 0],
         [3, 0, 0, ..., 2, 2, 0],
         ...,
         [4, 4, 0, ..., 2, 0, 0],
         [0, 4, 0, ..., 2, 0, 0],
         [0, 2, 0, ..., 2, 0, 0]]], dtype=int64),
 array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [5, 0, 0, ..., 0, 0, 0],
         ...,
         [3, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 1, 0],
         [0, 0, 0, ..., 0, 2, 0]]], dtype=int64),
 array([[[0, 3, 0, ..., 1, 0, 0],
         [3, 1, 0, ..., 1, 1, 

In [38]:
test.shape

(706, 1)

In [86]:
sample_df=pd.DataFrame(test, columns=['image_names'])
sample_df['emergency_or_not']= predictions1
#sample_df['pred2']= predictions2
#sample_df['pred3']= predictions3

In [87]:
sample_df.head()

image_names  emergency_or_not
0    1960.jpg                 0
1     668.jpg                 0
2    2082.jpg                 0
3     808.jpg                 1
4    1907.jpg                 0

In [89]:
sample_df.to_csv('sample_df.csv', index=False)